albert2804/transcendence

Makefile
make fclean also deletes the node_module and package-lock.json in the frontend folder.
also added "make prune" to easily run docker system prune -a -f
=> edited Makefile

backend/files/backend/api/views.py, backend/files/backend/backend/settings.py, backend/files/requirements.txt, frontend/app/components/BackendButton.vue
removed the rest_framework from django (not sure if we are allowed to use it) because it is not really needed for simple json responses.
=> removed rest_framework

backend/files/backend/backend/settings.py
Not sure how that got in there, fix container that won't start
=> Remove rest framwork

frontend/app/components/LocalPong.vue, frontend/app/components/NavBar.vue, frontend/app/pages/index_pong.vue, frontend/app/pages/localGame.vue
Fixed some issues like
- ball speed after hit
- pausing keyhook
included new NavBar and extended NavBar to able to click LocalGame
Please delete branch after merge
=> Local pong

backend/files/backend/remote_game/gameHandler.py
- After a ranked game ends, now also the CustomUser objects of the players gets filled. So now the Leaderboard gets his data ;)
=> save games

backend/files/backend/remote_game/pong.py, frontend/app/components/LocalPong.vue
Game logic update for improved UX
=> Modify game

frontend/app/components/NavBar.vue, frontend/app/components/leaderboard/Leaderboard.vue
=> Fix broken nav bar, remove duplicate login/logout element

backend/files/backend/custom_auth/views.py, frontend/app/components/login/LoginCard.vue, frontend/app/pages/redirect.vue
Error messages from the OAuth logins.
I was having issues with getting the url params to work for Oauth2 with the vue2 scripts, and they need to be able to delete each other's error messages so they don't show up twice, so I had to migrate some existing stuff into the vue3 <script setup> block. I don't think it broke anything - apologies if it did.
=> Error messages

frontend/app/assets/styles/global.css, frontend/app/components/NavBar.vue, frontend/app/components/game/GameField.vue, frontend/app/components/game/GameModal.vue, frontend/app/components/leaderboard/Leaderboard.vue, frontend/app/components/user/UserProfilePic.vue, frontend/app/pages/userinfopage.vue
Mostly styling changes, use nes-style buttons in the game modal, fix overly large modal.
=> 82 make it more beautiful httpswwwyoutubecomwatchv=fcjahaqhrww

frontend/app/components/settings/SettingsName.vue
Somehow, layouts from the settings modules get applied to the main page.
=> Fix borked buttons on Login card

backend/files/backend/custom_auth/views.py, frontend/app/components/login/LoginCard.vue
Fixed the issue, also fixed 42 oauth which I broke in an earlier merge request.
=> 127 errorsuccess messages on login not cleared properly

frontend/app/assets/styles/global.css, frontend/app/components/chat/ChatBox.vue, frontend/app/components/chat/ChatButton.vue, frontend/app/components/game/GameButton.vue, frontend/app/components/settings/SettingsBtn.vue
we had problems with our mouse size (because of conflicts between bootstrap and nes css).
Now I added .clickable to the assets/styles/global.css. You can use it in your component, if your buttons or other stuff uses the small click icon from bootstrap.
If you have a repeating component, that should use the big click icon every time, you can also add this class to the .clickable in the global.css
=> same mouseSize

frontend/app/components/login/LoginCard.vue
repaired the initial loadingSpinner
=> initial spinner

frontend/app/components/NavBar.vue, frontend/app/components/chat/ChatBox.vue, frontend/app/layouts/default.vue
- small change in the chatBox (link to profile page)
- in the default layout changed <slot /> to <router-view :key="$route.fullPath"></router-view>. So now the full path gets checked when navigating through sites (auto reloads when path/parameter changed)
- Removed reloadUserProfile() from NavBar because it's not needed anymore
=> ProfilePage-Navigation

backend/files/backend/remote_game/consumers.py, backend/files/backend/remote_game/pong.py, frontend/app/components/game/GameField.vue, frontend/app/components/game/GameModal.vue
- Implemented a countdown at game start
- close modal when game websocket disconnects (for example backend gets disconnectd...)
=> 151 countdown

backend/files/backend/api/urls.py, backend/files/backend/api/views.py, backend/files/backend/chat/consumers.py, backend/files/backend/remote_game/consumers.py, backend/files/backend/users/get_all_users.py
Added some functions to the API
=> Api functions

frontend/app/pages/index.vue
fixes the error message from the Vue Router, that it can not find the background image (frontend)
=> background fix

frontend/app/components/settings/SettingsBtn.vue
changed: 
checking for undefined
to ->
checking for the current integer
and added a parent div around it
=> fix for hydration mismatch in settingspw

backend/files/backend/api/views.py
Get rid of that pesky error in the browser console on page load
=> Fix error in the browser console when anon user checks 2fa status, cleanup

backend/files/backend/api/views.py, frontend/app/components/login/LoginCard.vue, frontend/app/components/settings/SettingsBtn.vue, frontend/app/layouts/default.vue, frontend/app/store/index.js
-hides the "change password" and "enable/disbale 2F auth" Buttons for 42 users
=> hide buttons for 42 users

frontend/app/components/tournament/ListTournament.vue, frontend/app/pages/tournament.vue, frontend/app/pages/userinfopage.vue
- bugfix issue #234 (changed beforeDestroy() to beforeUnmount())
- hide Tournamentpage and userinfopage from unregistered users
=> bugfix and hide pages

frontend/app/nuxt.config.ts
removes all console logs in the production code.
During development you can still use console logs ;)
=> No more console log

frontend/app/components/game/GameField.vue, frontend/app/components/settings/SettingsMap.vue, frontend/app/components/settings/SettingsName.vue, frontend/app/components/settings/SettingsPic.vue, frontend/app/components/settings/SettingsPw.vue, frontend/app/components/user/UserInfo.vue, frontend/app/package.json
- updated nuxt to 3.11.1
- removed @nuxt/devtools
- changed a few things with the maps :)
=> Some small fixes

backend/files/backend/tournament/logic.py, frontend/app/assets/styles/global.css, frontend/app/components/NavBar.vue, frontend/app/components/UserSearchDropdown.vue, frontend/app/components/tournament/FormTournament.vue, frontend/app/components/tournament/ListTournament.vue, frontend/app/pages/tournament.vue
some small adjustment with the search field and fixed the issue #243
=> Refining tournament

backend/files/backend/users/views.py
=> Update views.py handleProfilePic

Makefile, frontend/app/components/game/GameField.vue, frontend/app/components/settings/SettingsMap.vue
fixed the problem, that the backgrund doesn't appear when starting game over chat.
also didi some othe smaller changes like other backgrounds...
=> Game background fix

frontend/app/components/game/GameModal.vue, frontend/app/nuxt.config.ts, frontend/app/package.json
I realized that the nuxt2 errors came from the use of VueUse.
I used it for the fullscreen mode.
=> remove vueuse

backend/files/backend/remote_game/gravity.py, backend/files/backend/remote_game/pong.py
=> Fixed intersection for sure this time
